# Generated by Django 6.1.1 on 2026-09-24 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('external_id', models.PositiveIntegerField(unique=True)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('logo_url', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('external_id', models.PositiveIntegerField(unique=True)),
                ('crest_url', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Standing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('played', models.PositiveSmallIntegerField(default=0)),
                ('won', models.PositiveSmallIntegerField(default=0)),
                ('drawn', models.PositiveSmallIntegerField(default=0)),
                ('lost', models.PositiveSmallIntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
                ('goal_difference', models.IntegerField(default=0)),
                ('season', models.CharField(max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='matches.league')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='standings', to='matches.team')),
            ],
            options={
                'ordering': ['position'],
                'constraints': [models.UniqueConstraint(fields=('league', 'team', 'season'), name='unique_standing_league_team_season')],
            },
        ),
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.PositiveIntegerField(unique=True)),
                ('kickoff_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('LIVE', 'Live'), ('HALFTIME', 'Halftime'), ('FINISHED', 'Finished'), ('POSTPONED', 'Postponed')], default='SCHEDULED', max_length=20)),
                ('minute', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('home_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('away_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('matchday', models.CharField(blank=True, max_length=150)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fixtures', to='matches.league')),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='away_fixtures', to='matches.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='home_fixtures', to='matches.team')),
            ],
            options={
                'ordering': ['kickoff_at'],
                'indexes': [models.Index(fields=['status', 'kickoff_at'], name='matches_fix_status_548108_idx'), models.Index(fields=['league', 'kickoff_at'], name='matches_fix_league__d96fd1_idx')],
            },
        ),
    ]
