# Generated by Django 6.1.1 on 2026-09-24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [
        migrations.CreateModel(name="Category", fields=[
            ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ("name", models.CharField(max_length=100)), ("slug", models.SlugField(unique=True)),
        ], options={"verbose_name_plural": "categories", "ordering": ["name"]}),
        migrations.CreateModel(name="Tag", fields=[
            ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ("name", models.CharField(max_length=100, unique=True)),
        ], options={"ordering": ["name"]}),
        migrations.CreateModel(name="Author", fields=[
            ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ("display_name", models.CharField(max_length=150)), ("bio", models.TextField(blank=True)),
            ("user", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
        ]),
        migrations.CreateModel(name="Article", fields=[
            ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ("title", models.CharField(max_length=255)), ("slug", models.SlugField(blank=True, unique=True)),
            ("body", models.TextField(help_text="Markdown content")), ("hero_image", models.URLField(blank=True)),
            ("published_at", models.DateTimeField(blank=True, null=True)), ("is_breaking", models.BooleanField(default=False)),
            ("is_top_story", models.BooleanField(default=False)), ("top_story_order", models.PositiveSmallIntegerField(blank=True, null=True)),
            ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)),
            ("author", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="articles", to="articles.author")),
            ("category", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="articles", to="articles.category")),
            ("tags", models.ManyToManyField(blank=True, related_name="articles", to="articles.tag")),
        ], options={"ordering": ["-published_at", "-created_at"]}),
    ]
