# Generated by Django 6.1.1 on 2026-09-24 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('visitor_hash', models.CharField(db_index=True, max_length=64)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='articles.article')),
            ],
            options={
                'indexes': [models.Index(fields=['article', 'viewed_at'], name='articles_ar_article_adae08_idx'), models.Index(fields=['article', 'visitor_hash', 'viewed_at'], name='articles_ar_article_a0137a_idx')],
            },
        ),
    ]
