# Generated by Django 6.1.1 on 2026-09-24 22:20

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


def install_search_infrastructure(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return

    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            """
            CREATE INDEX article_search_gin
            ON articles_article USING gin (search_vector)
            """
        )
        cursor.execute(
            """
            CREATE INDEX video_search_gin
            ON articles_videopost USING gin (search_vector)
            """
        )
        cursor.execute(
            """
            CREATE OR REPLACE FUNCTION update_article_search_vector()
            RETURNS trigger AS $$
            BEGIN
                NEW.search_vector :=
                    setweight(to_tsvector('simple', coalesce(NEW.title, '')), 'A') ||
                    setweight(to_tsvector('simple', coalesce(NEW.body, '')), 'B');
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;
            """
        )
        cursor.execute(
            """
            CREATE OR REPLACE FUNCTION update_video_search_vector()
            RETURNS trigger AS $$
            BEGIN
                NEW.search_vector :=
                    setweight(to_tsvector('simple', coalesce(NEW.title, '')), 'A') ||
                    setweight(to_tsvector('simple', coalesce(NEW.description, '')), 'B');
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;
            """
        )
        cursor.execute(
            """
            CREATE TRIGGER article_search_vector_update
            BEFORE INSERT OR UPDATE OF title, body ON articles_article
            FOR EACH ROW EXECUTE FUNCTION update_article_search_vector()
            """
        )
        cursor.execute(
            """
            CREATE TRIGGER video_search_vector_update
            BEFORE INSERT OR UPDATE OF title, description ON articles_videopost
            FOR EACH ROW EXECUTE FUNCTION update_video_search_vector()
            """
        )
        cursor.execute(
            """
            UPDATE articles_article
            SET search_vector =
                setweight(to_tsvector('simple', coalesce(title, '')), 'A') ||
                setweight(to_tsvector('simple', coalesce(body, '')), 'B')
            """
        )
        cursor.execute(
            """
            UPDATE articles_videopost
            SET search_vector =
                setweight(to_tsvector('simple', coalesce(title, '')), 'A') ||
                setweight(to_tsvector('simple', coalesce(description, '')), 'B')
            """
        )


def remove_search_infrastructure(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return

    with schema_editor.connection.cursor() as cursor:
        cursor.execute("DROP TRIGGER IF EXISTS article_search_vector_update ON articles_article")
        cursor.execute("DROP TRIGGER IF EXISTS video_search_vector_update ON articles_videopost")
        cursor.execute("DROP FUNCTION IF EXISTS update_article_search_vector()")
        cursor.execute("DROP FUNCTION IF EXISTS update_video_search_vector()")
        cursor.execute("DROP INDEX IF EXISTS article_search_gin")
        cursor.execute("DROP INDEX IF EXISTS video_search_gin")


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_videopost'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='videopost',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(editable=False, null=True),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(install_search_infrastructure, remove_search_infrastructure),
            ],
            state_operations=[
                migrations.AddIndex(
                    model_name="article",
                    index=django.contrib.postgres.indexes.GinIndex(
                        fields=["search_vector"], name="article_search_gin"
                    ),
                ),
                migrations.AddIndex(
                    model_name="videopost",
                    index=django.contrib.postgres.indexes.GinIndex(
                        fields=["search_vector"], name="video_search_gin"
                    ),
                ),
            ],
        ),
    ]
