"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from datetime import date
from pathlib import Path

import environ
from celery.schedules import crontab

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings (development only).
env = environ.Env(
    DEBUG=(bool, False),
)
environ.Env.read_env(BASE_DIR / ".env")

SECRET_KEY = env("SECRET_KEY")
DEBUG = env("DEBUG")
ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=["localhost", "127.0.0.1"])


INSTALLED_APPS = [
    'daphne',
    'channels',
    'config.apps.ProjectAdminConfig',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'django.contrib.postgres',
    'articles',
    'matches',
    'ticker',
    'newsletter',
    'accounts',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'
ASGI_APPLICATION = 'config.asgi.application'


DATABASES = {
    "default": env.db("DATABASE_URL")
}


AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "staticfiles"

CORS_ALLOWED_ORIGINS = env.list("CORS_ALLOWED_ORIGINS", default=[])
CORS_ALLOW_ALL_ORIGINS = env.bool("CORS_ALLOW_ALL_ORIGINS", default=DEBUG)

REDIS_URL = env("REDIS_URL", default="redis://127.0.0.1:6379/0")
REDIS_CHANNEL_URL = env("REDIS_CHANNEL_URL", default="redis://127.0.0.1:6379/2")
REDIS_CACHE_URL = env("REDIS_CACHE_URL", default=REDIS_URL)
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": REDIS_CACHE_URL,
    },
}
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {"hosts": [REDIS_CHANNEL_URL]},
    },
}


ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=[])
CSRF_TRUSTED_ORIGINS = env.list("CSRF_TRUSTED_ORIGINS", default=[])
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

CELERY_BROKER_URL = REDIS_URL
CELERY_RESULT_BACKEND = REDIS_URL
CELERY_TIMEZONE = TIME_ZONE
CELERY_WORKER_DISABLE_RATE_LIMITS = True
CELERY_WORKER_CONCURRENCY = 4
CELERY_TASK_DEFAULT_RATE_LIMIT = None
CELERY_BEAT_MAX_LOOP_INTERVAL = 5
CELERY_BEAT_SCHEDULE = {
    "recompute-trending": {
        "task": "articles.tasks.recompute_trending",
        "schedule": 900.0,
    },
    "cleanup-old-article-views": {
        "task": "articles.tasks.cleanup_old_article_views",
        "schedule": 86400.0,
    },
    "sync-daily-fixtures": {
        "task": "matches.tasks.sync_daily_fixtures_task",
        # Run 10 minutes after the hour so it does not compete with the
        # minute-based live-score task at the top of the hour.
        "schedule": crontab(minute=10),
    },
    "sync-live-scores": {
        "task": "matches.tasks.sync_live_scores_task",
        "schedule": 60.0,
    },
    "sync-standings": {
        "task": "matches.tasks.sync_standings_task",
        "schedule": crontab(hour=6, minute=30),
    },
}

API_FOOTBALL_KEY = env("API_FOOTBALL_KEY", default="")
API_FOOTBALL_BASE_URL = env(
    "API_FOOTBALL_BASE_URL",
    default="https://v3.football.api-sports.io",
)
TRACKED_LEAGUES = env.list(
    "TRACKED_LEAGUES",
    default=["39", "2", "3", "848", "6", "78", "140", "135", "61"],
)
SEASONAL_LEAGUES = {
    6: [
        (date(2025, 12, 21), date(2026, 1, 18)),
        (date(2027, 6, 19), date(2027, 7, 17)),
    ],
}
DAILY_REQUEST_BUDGET = env.int("DAILY_REQUEST_BUDGET", default=100)
DAILY_REQUEST_HEADROOM = env.int("DAILY_REQUEST_HEADROOM", default=10)

REST_FRAMEWORK = {
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": env.int("API_PAGE_SIZE", default=20),
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_THROTTLE_CLASSES": (
        "rest_framework.throttling.ScopedRateThrottle",
    ),
    "DEFAULT_THROTTLE_RATES": {
        "newsletter_subscribe": "5/minute",
    },
}


MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}
