# Generated by Django 6.1.1 on 2026-09-24 22:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0002_articleview'),
    ]

    operations = [
        migrations.CreateModel(
            name='TickerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=200)),
                ('link', models.URLField(blank=True)),
                ('posted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_live', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticker_entries', to='articles.article')),
            ],
            options={
                'ordering': ['-posted_at'],
            },
        ),
    ]
