import re

import bleach
import markdown
from rest_framework import serializers

from .models import Article, Author, Category, Tag, VideoPost

_ALLOWED_HTML_TAGS = {
    "a", "article", "aside", "b", "blockquote", "br", "code", "del", "div",
    "em", "figcaption", "figure", "h1", "h2", "h3", "h4", "h5", "h6",
    "hr", "i", "img", "li", "ol", "p", "pre", "s", "span", "strong",
    "sub", "sup", "table", "tbody", "td", "th", "thead", "tr", "u", "ul",
}
_ALLOWED_HTML_ATTRIBUTES = {
    "a": ["href", "name", "title"],
    "img": ["alt", "src", "title"],
    "*": ["class"],
}
_AI_ARTIFACT_PATTERNS = (
    re.compile(r"(?is)\b(?:here(?:'|’)s|here is|sure,\s*here(?:'|’)s|certainly,?)\b.*?(?:\n|$)"),
    re.compile(r"(?is)\b(?:generated by|written by|assisted by|powered by)\s+(?:chatgpt|openai|an ai|ai)\b.*"),
    re.compile(r"(?is)\b(?:chatgpt|openai|ai[- ]?generated)\b.*"),
)


def _clean_article_markdown(raw_body: str) -> str:
    if not raw_body:
        return ""
    cleaned = raw_body.strip()
    for pattern in _AI_ARTIFACT_PATTERNS:
        cleaned = pattern.sub(" ", cleaned)
    cleaned = re.sub(r"\n{3,}", "\n\n", cleaned)
    cleaned = re.sub(r"\s{2,}", " ", cleaned)
    return cleaned.strip()


def render_article_body(raw_body: str) -> str:
    cleaned = _clean_article_markdown(raw_body)
    if not cleaned:
        return ""
    html = markdown.markdown(
        cleaned,
        extensions=["extra", "sane_lists", "tables", "fenced_code"],
    )
    return bleach.clean(
        html,
        tags=_ALLOWED_HTML_TAGS,
        attributes=_ALLOWED_HTML_ATTRIBUTES,
        protocols=["http", "https", "mailto"],
        strip_comments=True,
    )


class CategorySerializer(serializers.ModelSerializer):
    class Meta:
        model = Category
        fields = ("name", "slug")


class TagSerializer(serializers.ModelSerializer):
    class Meta:
        model = Tag
        fields = ("name",)


class AuthorSerializer(serializers.ModelSerializer):
    class Meta:
        model = Author
        fields = ("display_name", "bio")


class ArticleSerializer(serializers.ModelSerializer):
    category = CategorySerializer(read_only=True)
    tags = TagSerializer(many=True, read_only=True)
    author = AuthorSerializer(read_only=True)
    read_time = serializers.ReadOnlyField()
    body = serializers.SerializerMethodField()

    def get_body(self, obj: Article) -> str:
        return render_article_body(obj.body or "")

    class Meta:
        model = Article
        fields = (
            "title", "slug", "body", "category", "tags", "author", "hero_image",
            "published_at", "is_breaking", "is_top_story", "top_story_order",
            "created_at", "updated_at", "read_time",
        )


class ArticleHeadlineSerializer(serializers.ModelSerializer):
    category = CategorySerializer(read_only=True)
    read_time = serializers.ReadOnlyField()

    class Meta:
        model = Article
        fields = ("title", "slug", "category", "hero_image", "published_at", "is_breaking", "read_time")


class VideoPostSerializer(serializers.ModelSerializer):
    category = CategorySerializer(read_only=True)

    class Meta:
        model = VideoPost
        fields = (
            "title", "slug", "description", "embed_url", "thumbnail_url",
            "duration_seconds", "category", "published_at", "created_at",
        )
